#include "VideoEncoding.h"
#include "VideoDecoding.h"

int main()
{
    VideoEncoding videoEncoding;
    VideoDecoding videoDecoding;
    //encode
    // Using the .yuv file generated by the VideoDecoder project 
    const char *inFile = "../assets/Sample_1280x534_yuv420p.yuv";
    const char *outFile = "../assets/Sample1.h264";

    videoEncoding.init();

    // Configure AVCodecContext parameters Manually
    videoEncoding.initCodecContext();

    videoEncoding.readFrameProc(inFile, outFile);

    //decode
    const char *fileName = "../assets/Sample1.h264";

    videoDecoding.init(fileName);

    if (videoDecoding.findStreamIndex()) {
        return 1;
    }

    // Initialize the AVCodecContext
    if (videoDecoding.initCodecContext()) {
        return 1;
    }
    videoDecoding.readFrameProc();


}